nav:
  - Introduction: './0-introduction/index.md'
  - "Abyss 1: Beginning Abyss - Royal Capital":
      - Maps: './1-beginning-abyss/maps.md'
      - Requests: './1-beginning-abyss/requests.md'
      - Important Request / Greater Warped One: './1-beginning-abyss/important-request-gwo.md'
  - "Abyss 2: Trade Waterways - Port Town":
      - Maps: './2-port-town-grand-legion/maps.md'
      - Requests: './2-port-town-grand-legion/requests.md'
      - Important Request / Greater Warped One: './2-port-town-grand-legion/important-request-gwo.md'
  - "Abyss 3: Impregnable Fortress - Guarda":
      - Maps: './3-guarda-fortress/maps.md'
      - Requests: './3-guarda-fortress/requests.md'
      - Important Request / Greater Warped One: './3-guarda-fortress/important-request-gwo.md'
      - Misc Bosses:
          - Morgus, God of Death: './3-guarda-fortress/misc-bosses/morgus-god-of-death.md'
  - Ancient Mausoleum: './ancient-mausoleum/maps.md'
  - Dens:
      - Den of Earth: './dens/den-of-earth.md'
      - Den of Fire: './dens/den-of-fire.md'
      - Den of Wind: './dens/den-of-wind.md'
      - Den of Light: './dens/den-of-light.md'
  - Grade Exams: './grade-exams/maps.md'
  - Request from an Ally:
      - Symbol of Alliance: './request-from-an-ally/symbol-of-alliance.md'
      - Arna's Past: './request-from-an-ally/arnas-past.md'
